//translate above to ts
export const status = {
  GLOBAL_QUOTA_NOT_ENOUGH: "GLOBAL_QUOTA_NOT_ENOUGH",
  QUOTA_NOT_ENOUGH: "QUOTA_NOT_ENOUGH",
  USER_QUOTA_UPDATED: "USER_QUOTA_UPDATED",
  SERVICE_QUOTA_UPDATED: "SERVICE_QUOTA_UPDATED",
  OK: "OK",
  FAILED: "FAILED",
  SUBSCRIPTION_CANCEL_AT_PERIOD_END: "SUBSCRIPTION_CANCEL_AT_PERIOD_END",
  SUBSCRIPTION_RESUME_AT_PERIOD_END: "SUBSCRIPTION_RESUME_AT_PERIOD_END",
};
